USE [master]
GO

/****** Object:  Database [DBADatabase]    Script Date: 14/05/2016 10:14:58 ******/
CREATE DATABASE [DBADatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBADatabase', FILENAME = N'C:\MSSQL\Data\DBADatabase.mdf' , SIZE = 262144KB , MAXSIZE = 5242880KB , FILEGROWTH = 262144KB )
 LOG ON 
( NAME = N'DBADatabase_log', FILENAME = N'C:\MSSQL\Logs\DBADatabase_log.ldf' , SIZE = 786432KB , MAXSIZE = 5242880KB , FILEGROWTH = 262144KB )
GO

ALTER DATABASE [DBADatabase] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBADatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBADatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBADatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBADatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBADatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBADatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBADatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBADatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBADatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBADatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBADatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBADatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBADatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBADatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBADatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBADatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBADatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBADatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBADatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBADatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBADatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBADatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBADatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBADatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [DBADatabase] SET  MULTI_USER 
GO

ALTER DATABASE [DBADatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBADatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBADatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBADatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBADatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBADatabase] SET QUERY_STORE = OFF
GO

USE [DBADatabase]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DBADatabase] SET  READ_WRITE 
GO


